- name: Install NFS server
  ansible.builtin.package:
    name: nfs-utils
    state: present

- name: Disable nfsv3
  ansible.builtin.include_tasks: nfsv4-only.yaml
  when: nfs_nfsv4_only

- name: Setup kTLS for NFS encryption
  ansible.builtin.include_tasks: ktls.yaml
  when: nfs_ktls

- name: Setup NFS exports
  ansible.builtin.include_tasks: exports.yaml
  when: nfs_exports is defined

- name: Allow NFS traffic through the firewall
  ansible.builtin.include_tasks: firewall.yaml
  when: nfs_firewall_disable
